### ISSUE TITLE
Transaction-related errors coming from SQL Server continuously

### ISSUE THREAD

**Issue by sboutsis** [HangfireIO/Hangfire#1612]
Hi,
I'm using Hangfire 1.6.28, with Hangfire.SqlServer. My worker count is the default (20), and the queue poll interval is 15 seconds. I have not enabled SlidingInvisibilityTimeout yet.
I have a single background job that is scheduled to run once every hour. For testing purposes, it does nothing (meaning that its body just returns, immediately).

In the development and QA environments, everything works fine. However, soon after I moved the application to the production environment, errors started to show up:

```
Error occurred during execution of 'Worker #54915702' process. Execution will be retried (attempt #2) in 00:00:03 seconds. System.Data.SqlClient.SqlException (0x80131904): The server failed to resume the transaction. Desc:c800000171.
The transaction active in this session has been committed or aborted by another session.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj)
   at System.Data.SqlClient.TdsParser.TdsExecuteTransactionManagerRequest(Byte[] buffer, TransactionManagerRequestType request, String transactionName, TransactionManagerIsolationLevel isoLevel, Int32 timeout, SqlInternalTransaction transaction, TdsParserStateObject stateObj)
   at System.Data.SqlClient.SqlInternalConnectionTds.ExecuteTransactionYukon(TransactionRequest transactionRequest, String transactionName, IsolationLevel iso, SqlInternalTransaction internalTransaction)
   at System.Data.SqlClient.SqlInternalConnection.BeginSqlTransaction(IsolationLevel iso, String transactionName, Boolean shouldReconnect)
   at System.Data.SqlClient.SqlConnection.BeginTransaction(IsolationLevel iso, String transactionName)
   at System.Data.SqlClient.SqlConnection.BeginDbTransaction(IsolationLevel isolationLevel)
   at Hangfire.SqlServer.SqlServerJobQueue.DequeueUsingTransaction(String[] queues, CancellationToken cancellationToken)
   at Hangfire.SqlServer.SqlServerJobQueue.Dequeue(String[] queues, CancellationToken cancellationToken)
   at Hangfire.SqlServer.SqlServerConnection.FetchNextJob(String[] queues, CancellationToken cancellationToken)
   at Hangfire.Server.Worker.Execute(BackgroundProcessContext context)
   at Hangfire.Server.AutomaticRetryProcess.Execute(BackgroundProcessContext context)
```
This started happening a week ago, and has not stopped since that point. Every worker seems to be getting the same error, then retries, same thing happens.

Sometimes I get other errors that seem to be related, like this one:

```
Error occurred during execution of 'Worker #a12cbeef' process. Execution will be retried (attempt #3) in 00:00:04 seconds. System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Data.SqlClient.SqlInternalTransaction.GetServerTransactionLevel()
   at System.Data.SqlClient.SqlInternalTransaction.CheckTransactionLevelAndZombie()
   at System.Data.SqlClient.SqlInternalTransaction.Rollback()
   at System.Data.SqlClient.SqlTransaction.Dispose(Boolean disposing)
   at Hangfire.SqlServer.SqlServerJobQueue.DequeueUsingTransaction(String[] queues, CancellationToken cancellationToken)
   at Hangfire.SqlServer.SqlServerJobQueue.Dequeue(String[] queues, CancellationToken cancellationToken)
   at Hangfire.SqlServer.SqlServerConnection.FetchNextJob(String[] queues, CancellationToken cancellationToken)
   at Hangfire.Server.Worker.Execute(BackgroundProcessContext context)
   at Hangfire.Server.AutomaticRetryProcess.Execute(BackgroundProcessContext context)
```
or this one:

```
Failed to process the job '135': an exception occurred. System.Data.SqlClient.SqlException (0x80131904): New transaction is not allowed because there are other threads running in the session.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj)
   at System.Data.SqlClient.TdsParser.TdsExecuteTransactionManagerRequest(Byte[] buffer, TransactionManagerRequestType request, String transactionName, TransactionManagerIsolationLevel isoLevel, Int32 timeout, SqlInternalTransaction transaction, TdsParserStateObject stateObj)
   at System.Data.SqlClient.SqlInternalConnectionTds.ExecuteTransactionYukon(TransactionRequest transactionRequest, String transactionName, IsolationLevel iso, SqlInternalTransaction internalTransaction)
   at System.Data.SqlClient.SqlInternalConnection.BeginSqlTransaction(IsolationLevel iso, String transactionName, Boolean shouldReconnect)
   at System.Data.SqlClient.SqlConnection.BeginTransaction(IsolationLevel iso, String transactionName)
   at System.Data.SqlClient.SqlConnection.BeginDbTransaction(IsolationLevel isolationLevel)
   at Hangfire.SqlServer.SqlServerStorage.<>c__DisplayClass30_0`1.<UseTransaction>b__0(DbConnection connection)
   at Hangfire.SqlServer.SqlServerStorage.UseConnection[T](DbConnection dedicatedConnection, Func`2 func)
   at Hangfire.SqlServer.SqlServerStorage.UseTransaction[T](DbConnection dedicatedConnection, Func`3 func, Nullable`1 isolationLevel)
   at Hangfire.SqlServer.SqlServerStorage.UseTransaction(DbConnection dedicatedConnection, Action`2 action)
   at Hangfire.SqlServer.SqlServerWriteOnlyTransaction.Commit()
   at Hangfire.States.BackgroundJobStateChanger.ChangeState(StateChangeContext context)
   at Hangfire.Server.Worker.TryChangeState(BackgroundProcessContext context, IStorageConnection connection, IFetchedJob fetchedJob, IState state, String[] expectedStates, CancellationToken cancellationToken)
```

or even this one: 

```
Error occurred during execution of 'Worker #dde5496a' process. Execution will be retried (attempt #4) in 00:00:14 seconds. Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: {. Path '', line 1, position 1.
   at Newtonsoft.Json.JsonTextReader.ReadNumberValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsInt32()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Hangfire.Common.JobHelper.FromJson[T](String value)
   at Hangfire.AutomaticRetryAttribute.OnStateElection(ElectStateContext context)
   at Hangfire.Profiling.ProfilerExtensions.InvokeAction[TInstance](InstanceAction`1 tuple)
   at Hangfire.Profiling.SlowLogProfiler.InvokeMeasured[TInstance,TResult](TInstance instance, Func`2 action, String message)
   at Hangfire.Profiling.ProfilerExtensions.InvokeMeasured[TInstance](IProfiler profiler, TInstance instance, Action`1 action, String message)
   at Hangfire.States.StateMachine.ApplyState(ApplyStateContext initialContext)
   at Hangfire.States.BackgroundJobStateChanger.ChangeState(StateChangeContext context)
   at Hangfire.Server.Worker.TryChangeState(BackgroundProcessContext context, IStorageConnection connection, IFetchedJob fetchedJob, IState state, String[] expectedStates, CancellationToken cancellationToken)
   at Hangfire.Server.Worker.Execute(BackgroundProcessContext context)
   at Hangfire.Server.AutomaticRetryProcess.Execute(BackgroundProcessContext context)
```

On the dashboard, I can see that the majority of the scheduled job invocations show up as "succeeded", while some of them show up as "processing". I've got a few that are stuck in the processing state for a week.

The only difference between the dev and prod environments is that the SQL server version on dev is 2008, while in prod it's 2016. I even tested the application on dev, using an SQL server 2016 instance, but the problem is not reproducible.

I'm not sure about what to check in order to troubleshoot this situation. Any ideas?
Thanks in advance.

**Comment by pieceofsummer** [comment]
When you say “I even tested the application on dev, using an SQL server 2016 instance”, do you mean the exact MSSQL instance/database the prod server uses, or just another test server with newer version of MSSQL?

Have you tried creating a new database in prod environment, so Hangfire initialize it’s tables from scratch? This would allow to rule out any replication/backup/maintenance jobs DBAs tend to set up for production databases.

**Comment by sboutsis** [comment]
@pieceofsummer, I mean another server with the same version that we're using in production.
And yes, I tried to re-initialize the database.

**Comment by pieceofsummer** [comment]
I would try various combinations, like code running on dev but using a database on prod DB server for storage, and vice versa.

I’m also very curious to see a value for "RetryCount" parameter for the last stack trace. There’s clearly some object serialized there instead of an integer. Have you configured any JSON serialization settings which may result in this?

Also, any particular reason you’re staying on the old 1.6.x version and not updating to 1.7.x?

**Comment by odinserj** [comment]
Looks like the protocol is broken – you have strange `NullReferenceException` in internal classes of `System.Data.SqlClient` package, wrong characters received and different problems with session. Looks like you are either using something like .NET Core 1.X or your version of `System.Data.SqlClient` package is too old.

Try upgrading your `System.Data.SqlClient` at least to version 4.4.0 (but better use 4.8.0) – there were a lot of problems in early days of .NET Core, but almost all of them are fixed now. If that package is not referenced in your project directly, install it explicitly.

This should have, but if not – tell us version of .NET Framework or .NET Core you are using.

**Comment by sboutsis** [comment]
@pieceofsummer, unfortunately I can't mix the environments, because of strict company policies.
The JSON serialization settings are configured like this:
```
options.SerializerSettings.Culture = System.Globalization.CultureInfo.InvariantCulture;
options.SerializerSettings.DateTimeZoneHandling = Newtonsoft.Json.DateTimeZoneHandling.Utc;
options.SerializerSettings.DateFormatHandling = Newtonsoft.Json.DateFormatHandling.IsoDateFormat;
options.SerializerSettings.NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore;
```
Finally, I was planning to upgrade to 1.7.x at some point, but right now I'm hesitant to do so because of any breaking changes such an upgrade might introduce.

@odinserj I'm on .NET Core 2.2 and my ```System.Data.SqlClient``` version is 4.6.0.

**Comment by pieceofsummer** [comment]
So you basically cannot pinpoint a problem to the client (Hangfire), database server or the faulty connection in-between.

If updating the SqlServer package on the client (as suggested earlier) doesn’t help, you can try playing with the [network protocol setting in connection string](https://www.connectionstrings.com/define-sql-server-network-protocol/) and force named pipes or tcp/ip. Not sure which is configured as default on your system, but you should at least try the other one to see if that makes any difference.

**Comment by sboutsis** [comment]
So, I upgraded `System.Data.SqlClient` to version 4.8.0. Nothing changed. Furthermore, named pipes are disabled in the production environment (company policy), so I have to stick with TCP/IP.

Then, I removed the `DisableConcurrentExecution` attribute. That was it. I still don't have a proper technical explanation for this, but it seems that the long-lived locks taken by this attribute, somehow affect other queries. I'm now using short-lived locks, like @odinserj  does in the `MutexAttribute` that he wrote some time ago, and it seems to work without issues.

I'm still monitoring the system in case any exceptions come up. I'll update this thread if/when this happens.

**Comment by odinserj** [comment]
I still suspect the problem is related to System.Data.SqlClient. Hangfire was compiled as a portable library with the reference to `Microsoft.NETCore.Portable.Compatibility` to work in .NET Core applications in versions 1.6.X. And who knows how the support is implemented there, and it's still possible that framework references are modified somehow.

I simply don't see any other reasons for this weird behavior, I've double-checked and re-checked to ensure there's no usages of the same connection from multiple threads in Hangfire. I also didn't see such problems before.

Try upgrading to 1.7.9 as it have native .NET Core support without referencing the compatibility bits. Although its [Upgrade Guide](https://docs.hangfire.io/en/latest/upgrade-guides/upgrading-to-hangfire-1.7.html#upgrading-to-hangfire-1-7) may look comprehensive, it's not required if you aren't using any new features, 1.6.28 is forward compatible with it, and 1.7.X is backward compatible with all the data you've collected.

**Comment by odinserj** [comment]
Also Hangfire.SqlServer 1.6.X was compiled against .NET Standard 1.3, which have many missing APIs.

**Comment by xariosstewart** [comment]
Hi,
We're having the same problem with 1.7.9 & System.Data.SqlClient 4.8.0 hosted in a .NET Core 3.0 service with no DisableConcurrentExecution attributes:

`Hangfire.Processing.BackgroundExecution|Execution Worker is in the Failed state now due to an exception, execution will be retried no more than in 00:00:04 System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Data.SqlClient.SqlInternalTransaction.Rollback()
   at System.Data.SqlClient.SqlTransaction.Dispose(Boolean disposing)
   at Hangfire.SqlServer.SqlServerJobQueue.DequeueUsingTransaction(String[] queues, CancellationToken cancellationToken)
   at Hangfire.SqlServer.SqlServerJobQueue.Dequeue(String[] queues, CancellationToken cancellationToken)
   at Hangfire.SqlServer.SqlServerConnection.FetchNextJob(String[] queues, CancellationToken cancellationToken)
   at Hangfire.Server.Worker.Execute(BackgroundProcessContext context)
   at Hangfire.Server.BackgroundProcessDispatcherBuilder.ExecuteProcess(Guid executionId, Object state)
   at Hangfire.Processing.BackgroundExecution.Run(Action`2 callback, Object state)`
