### ISSUE TITLE
Cannot release the application lock (Database Principal: 'public', Resource: 'locks:expirationmanager')

### ISSUE THREAD

**Issue by willisterman** [HangfireIO/Hangfire#471]
I'm noticing the following error in our SQL Exception logging, about every 5 minutes:

System.Data.SqlClient.SqlException (0x80131904): Cannot release the application lock (Database Principal: 'public', Resource: 'locks:expirationmanager') because it is not currently held.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader)
   at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command)
   at Dapper.SqlMapper.Execute(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType)
   at Hangfire.SqlServer.SqlServerDistributedLock.Release(IDbConnection connection, String resource)
   at Hangfire.SqlServer.ExpirationManager.<>c__DisplayClass4.<Execute>b__0(SqlConnection connection)
   at Hangfire.SqlServer.SqlServerStorage.<>c__DisplayClassc.<UseConnection>b__b(SqlConnection connection)
   at Hangfire.SqlServer.SqlServerStorage.UseConnection[T](Func`2 func)
   at Hangfire.SqlServer.SqlServerStorage.UseConnection(Action`1 action)
   at Hangfire.SqlServer.ExpirationManager.Execute(CancellationToken cancellationToken)
   at Hangfire.Server.ServerProcessExtensions.Execute(IServerProcess process, BackgroundProcessContext context)
   at Hangfire.Server.AutomaticRetryProcess.Execute(BackgroundProcessContext context)

It doesn't appear to be stopping hangfire from processing jobs, but it is filling up my error log!

It didn't appear to happen before 1.5.0, and I've tried both 1.5.0 and 1.5.2 with the same problems.

**Comment by jpsprinsloo** [comment]
We are also experiencing a similar issue on one of our production servers. I'm currently using 1.5.0, will check with 1.5.2 if issue persist.

System.Data.SqlClient.SqlException (0x80131904): Cannot release the application lock (Database Principal: 'public', Resource: 'HangFire:recurring-jobs:lock') because it is not currently held.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader)
   at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command)
   at Hangfire.SqlServer.SqlServerDistributedLock.Release(IDbConnection connection, String resource)
   at Hangfire.SqlServer.SqlServerDistributedLock.Dispose()
   at Hangfire.Server.RecurringJobScheduler.Execute(BackgroundProcessContext context)
   at Hangfire.Server.AutomaticRetryProcess.Execute(BackgroundProcessContext context)
ClientConnectionId:9af75202-84e8-4272-bd85-0573210dbdc6

and 

System.Data.SqlClient.SqlException (0x80131904): Cannot release the application lock (Database Principal: 'public', Resource: 'HangFire:locks:schedulepoller') because it is not currently held.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader)
   at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command)
   at Hangfire.SqlServer.SqlServerDistributedLock.Release(IDbConnection connection, String resource)
   at Hangfire.SqlServer.SqlServerDistributedLock.Dispose()
   at Hangfire.Server.DelayedJobScheduler.EnqueueNextScheduledJob(BackgroundProcessContext context)
   at Hangfire.Server.DelayedJobScheduler.Execute(BackgroundProcessContext context)
   at Hangfire.Server.AutomaticRetryProcess.Execute(BackgroundProcessContext context)
ClientConnectionId:776869b9-d5a8-4822-8827-dfe0404042cd


I can't really spot a pattern on when it occurs, or why. I am still investigating the issue on my side, but as willisterman said, the jobs are still processed.

**Comment by willisterman** [comment]
I've been investigating this a little.  jpsprinsloo, is your SQL database an Azure database?

**Comment by jpsprinsloo** [comment]
SQL database

**Comment by willisterman** [comment]
Ah, ok then.  I was having issues replicating it on a dedicated SQL database, only getting it in Azure, but that means it must be something different.  Thanks.

**Comment by jpsprinsloo** [comment]
Mine is running as a windows service on a web server, different server than the SQL server, and different location/network. We recently moved the web server and I know there's a bit of latency on the network. About 84 ms delay on a ping between the servers.

Maybe check your network as well?

**Comment by odinserj** [comment]
Guys, thank you a lot for your investigation! The code was silly enough (you can see the changes – https://github.com/HangfireIO/Hangfire/commit/74f577e0278fd5837f7a564ccb06b7257a8dc731)  to release an application lock if it wasn't held when previous `ReleaseLock` method invocation thrown an exception while reading the results of an `sp_releaseapplock` execution.

I've released the fix with [Hangfire 1.5.3](https://github.com/HangfireIO/Hangfire/releases/tag/v1.5.3), so you can simply update it from NuGet.

**Comment by TheBeardedLlama** [comment]
I am using version 1.5.3 and am still seeing this error scattered around our error logs on a regular time interval, which is usually around 5 minutes.

An example:
2015-12-02 00:22:26,365 [7] ERROR Hangfire.SqlServer.ExpirationManager - Error occurred during execution of 'Hangfire.SqlServer.ExpirationManager' process. Execution will be retried (attempt 9 of 2147483647) in 00:01:11 seconds.
System.Data.SqlClient.SqlException (0x80131904): Cannot release the application lock (Database Principal: 'public', Resource: 'locks:expirationmanager') because it is not currently held.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader)
   at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command)
   at Hangfire.SqlServer.SqlServerDistributedLock.Release(IDbConnection connection, String resource)
   at Hangfire.SqlServer.ExpirationManager.<>c__DisplayClass4.<Execute>b__0(SqlConnection connection)
   at Hangfire.SqlServer.SqlServerStorage.<>c__DisplayClassc.<UseConnection>b__b(SqlConnection connection)
   at Hangfire.SqlServer.SqlServerStorage.UseConnection[T](Func`2 func)
   at Hangfire.SqlServer.ExpirationManager.Execute(CancellationToken cancellationToken)
   at Hangfire.Server.ServerProcessExtensions.Execute(IServerProcess process, BackgroundProcessContext context)
   at Hangfire.Server.AutomaticRetryProcess.Execute(BackgroundProcessContext context)
ClientConnectionId:d0c09be1-f7ab-4e89-9089-d304bdbff4cb

**Comment by MrKevHunter** [comment]
Also seeing this on Azure

**Comment by PyroJoke** [comment]
This issue is still exists with 1.5.3 version.

**Comment by robfarmergt** [comment]
I'm seeing this after upgrading to 1.5.4 too. Happening in an Azure SQL database. Is there a work around?

**Comment by contactsamie** [comment]
Happening in my case as well, using 1.5.3 with  Azure SQL database, jobs being en-queued from web server, jobs being processed from app hosted in windows service via topshelf. I did notice at some point ,however, I had mixed versions, 1.5.3 in processor and 1.5.0 in web, and correcting

Also after restarting the procesor I have the following log:

1,2016-05-02 14:32:48.1143,Debug,XXXXXXX.Jobs.Processor.Program,1,Setup XXXXXXX.Jobs.Processor starting ...,
2,2016-05-02 14:32:48.1299,Debug,XXXXXXX.Jobs.Processor.Program,1,Running topshelf setups...,
1,2016-05-02 14:32:48.4113,Debug,XXXXXXX.Jobs.Processor.Program,1,Setup XXXXXXX.Jobs.Processor starting ...,
2,2016-05-02 14:32:48.4268,Debug,XXXXXXX.Jobs.Processor.Program,1,Running topshelf setups...,
3,2016-05-02 14:32:48.5518,Debug,XXXXXXX.Jobs.Processor.BackgroundJobTopShelfClass,1,Initializing BackgroundJobTopShelfClass,
4,2016-05-02 14:32:49.0987,Info,Hangfire.SqlServer.SqlServerStorage,1,Start installing Hangfire SQL objects...,
5,2016-05-02 14:32:49.1768,Info,Hangfire.SqlServer.SqlServerStorage,1,Hangfire SQL objects installed.,
6,2016-05-02 14:32:49.1768,Info,Hangfire.SqlServer.SqlServerStorage,1,Start installing Hangfire SQL objects...,
7,2016-05-02 14:32:49.1924,Info,Hangfire.SqlServer.SqlServerStorage,1,Hangfire SQL objects installed.,
8,2016-05-02 14:32:49.2549,Info,Hangfire.BackgroundJobServer,5,Starting Hangfire Server,
9,2016-05-02 14:32:49.2549,Info,Hangfire.BackgroundJobServer,5,"Using job storage: 'SQL Server: tcp:xxxxxxx-xxxxxxxx.database.windows.net,1433@hangfire'.",
10,2016-05-02 14:32:49.2549,Info,Hangfire.BackgroundJobServer,5,Using the following options for SQL Server job storage:,
11,2016-05-02 14:32:49.2549,Info,Hangfire.BackgroundJobServer,5,    Queue poll interval: 00:00:15.,
12,2016-05-02 14:32:49.2549,Info,Hangfire.BackgroundJobServer,5,Using the following options for Hangfire Server:,
13,2016-05-02 14:32:49.2549,Info,Hangfire.BackgroundJobServer,5,    Worker count: 5.,
14,2016-05-02 14:32:49.2549,Info,Hangfire.BackgroundJobServer,5,    Listening queues: 'default'.,
15,2016-05-02 14:32:49.2549,Info,Hangfire.BackgroundJobServer,5,    Shutdown timeout: 00:00:15.,
16,2016-05-02 14:32:49.2549,Info,Hangfire.BackgroundJobServer,5,    Schedule polling interval: 00:00:15.,
17,2016-05-02 14:32:49.2862,Debug,Hangfire.Server.BackgroundProcessingServer,7,Background process 'BackgroundProcessingServer' started.,
18,2016-05-02 14:32:49.4893,Debug,Hangfire.Server.ServerHeartbeat,11,Background process 'ServerHeartbeat' started.,
19,2016-05-02 14:32:49.5050,Debug,Hangfire.Server.ServerWatchdog,12,Background process 'ServerWatchdog' started.,
20,2016-05-02 14:32:49.5050,Debug,Hangfire.SqlServer.ExpirationManager,13,Background process 'Hangfire.SqlServer.ExpirationManager' started.,
21,2016-05-02 14:32:49.5050,Debug,Hangfire.SqlServer.CountersAggregator,14,Background process 'Hangfire.SqlServer.CountersAggregator' started.,
22,2016-05-02 14:32:49.5050,Debug,Hangfire.Server.Worker,15,Background process 'Worker #c7cf1f4d' started.,
23,2016-05-02 14:32:49.5050,Debug,Hangfire.SqlServer.ExpirationManager,13,Removing outdated records from table 'AggregatedCounter'...,
24,2016-05-02 14:32:49.5050,Debug,Hangfire.SqlServer.CountersAggregator,14,Aggregating records in 'Counter' table...,
25,2016-05-02 14:32:49.5050,Debug,Hangfire.Server.Worker,16,Background process 'Worker #d8f8246b' started.,
26,2016-05-02 14:32:49.5050,Debug,Hangfire.Server.Worker,17,Background process 'Worker #805286c8' started.,
27,2016-05-02 14:32:49.5050,Debug,Hangfire.Server.Worker,18,Background process 'Worker #b5c28f1e' started.,
28,2016-05-02 14:32:49.5206,Debug,Hangfire.Server.Worker,19,Background process 'Worker #0ce06c3c' started.,
29,2016-05-02 14:32:49.5206,Debug,Hangfire.Server.DelayedJobScheduler,20,Background process 'DelayedJobScheduler' started.,
30,2016-05-02 14:32:49.5206,Debug,Hangfire.Server.RecurringJobScheduler,21,Background process 'RecurringJobScheduler' started.,
31,2016-05-02 14:32:49.5362,Debug,Hangfire.SqlServer.ExpirationManager,13,Removing outdated records from table 'Job'...,
32,2016-05-02 14:33:24.5961,Debug,Hangfire.SqlServer.ExpirationManager,13,Error xxxxxurred during execution of 'Hangfire.SqlServer.ExpirationManager' process. Execution will be retried (attempt 1 of 2147483647) in 00:00:01 seconds.,"System.Data.SqlClient.SqlException (0x80131904): Cannot release the application lock (Database Principal: 'public', Resource: 'locks:expirationmanager') because it is not currently held.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader)
   at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command)
   at Hangfire.SqlServer.SqlServerDistributedLock.Release(IDbConnection connection, String resource)
   at Hangfire.SqlServer.ExpirationManager.<>c__DisplayClass4.<Execute>b__0(SqlConnection connection)
   at Hangfire.SqlServer.SqlServerStorage.<>c__DisplayClassc.<UseConnection>b__b(SqlConnection connection)
   at Hangfire.SqlServer.SqlServerStorage.UseConnection[T](Func`2 func)
   at Hangfire.SqlServer.SqlServerStorage.UseConnection(Action`1 action)
   at Hangfire.SqlServer.ExpirationManager.Execute(CancellationToken cancellationToken)
   at Hangfire.Server.ServerProcessExtensions.Execute(IServerProcess process, BackgroundProcessContext context)
   at Hangfire.Server.AutomaticRetryProcess.Execute(BackgroundProcessContext context)
ClientConnectionId:c457e64f-8abb-43ee-83f1-734cf08e4dec
Error Number:1223,State:1,Class:16
ClientConnectionId before routing:bf52fba6-94c5-4136-a3e5-8869ad50cb52
Routing Destination:xxxxxx.tr6.xxxxxx-a.worker.database.windows.net,11005"
33,2016-05-02 14:33:25.6007,Debug,Hangfire.SqlServer.ExpirationManager,13,Removing outdated records from table 'AggregatedCounter'...,
34,2016-05-02 14:33:52.6034,Debug,Hangfire.SqlServer.ExpirationManager,13,Removing outdated records from table 'Job'...,
35,2016-05-02 14:34:27.6307,Info,Hangfire.SqlServer.ExpirationManager,13,Error xxxxxurred during execution of 'Hangfire.SqlServer.ExpirationManager' process. Execution will be retried (attempt 2 of 2147483647) in 00:00:03 seconds.,"System.Data.SqlClient.SqlException (0x80131904): Cannot release the application lock (Database Principal: 'public', Resource: 'locks:expirationmanager') because it is not currently held.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader)
   at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command)
   at Hangfire.SqlServer.SqlServerDistributedLock.Release(IDbConnection connection, String resource)
   at Hangfire.SqlServer.ExpirationManager.<>c__DisplayClass4.<Execute>b__0(SqlConnection connection)
   at Hangfire.SqlServer.SqlServerStorage.<>c__DisplayClassc.<UseConnection>b__b(SqlConnection connection)
   at Hangfire.SqlServer.SqlServerStorage.UseConnection[T](Func`2 func)
   at Hangfire.SqlServer.SqlServerStorage.UseConnection(Action`1 action)
   at Hangfire.SqlServer.ExpirationManager.Execute(CancellationToken cancellationToken)
   at Hangfire.Server.ServerProcessExtensions.Execute(IServerProcess process, BackgroundProcessContext context)
   at Hangfire.Server.AutomaticRetryProcess.Execute(BackgroundProcessContext context)
ClientConnectionId:d08d7723-5edc-4394-84e1-b113b1eac131
Error Number:1223,State:1,Class:16
ClientConnectionId before routing:84b1238f-5392-41cf-ad56-63eab305e4df
Routing Destination:xxxxxx.tr6.xxxxxx-a.worker.database.windows.net,11005"

**Comment by ppiazzolla** [comment]
We have the same error on 1.5.4 and in Azure. We get a lot of errors. Is this issue being monitored because it is set to closed since november? And if @ekaerik commit fixes it, maybe it should be a pull request then?

`(0x80131904): Cannot release the application lock (Database Principal: 'public', Resource: 'locks:expirationmanager')`

**Comment by ekaerik** [comment]
Eh, oups. Fiddled around with VS Git and the code. Got slightly confused while browsing the code and did that random change. It actually wont do anything, the same thing is basically done a few lines below.

**Comment by ppiazzolla** [comment]
@odinserj This is still an issue even if it's closed, would you recommend us doing a new issue of it? Don't want to break your flow.

**Comment by odinserj** [comment]
There was a problem with `ExpirationManager`, that was fixed in recent Hangfire 1.6.2 release, please see #628 for details. In short, before the fix, query analyzer issued `INDEX SCAN` operator during the record expiration, that caused the query to be very long.

Long-running transactions may be terminated after [5 minutes](https://social.msdn.microsoft.com/Forums/azure/en-US/efcd1185-123e-4fff-bdbb-4b2f903bf8ab/table-locking-in-sql-azure?forum=ssdsgetstarted#b3510059-bb40-4d7e-8ea2-fdc2cb7efdcb), and you get an exception in this case. The problem is that the original exception was hidden by a call to `Release` method call in a `finally` block. I'm planning to rework all the `finally` blocks and `Dispose` methods to not to throw any exception in 1.7.0 to prevent hiding original exception.

So you can:

1. Upgrade to Hangfire 1.6.2 to use new fast implementation of `ExpirationManager`.
2. Backport the fix to your version.
