### ISSUE TITLE
Redis timeouts...

### ISSUE THREAD

**Issue by dcorbett-radian** [HangfireIO/Hangfire#997]
I'm having a serious issue with long-running jobs.   These jobs take like 11 hours to run, with 10 of those being in a single call to a 3rd party library I don't control.

I have configured the RedisInvisibilityTimeout out to be 300 ( 5 hours - yes, maybe it should be 12+ ), but they are timing out at 2 hours, or less.

Sometimes it times out, sometimes it doesn't at all..   which is peculiar.   Often the job times out and requeues once, and then it doesn't time out the second time.   Sometimes it's about 2 hours, sometimes it's less -- such as 15 minutes.

Of course when it doesnt timeout and keeps running, it's "invisible".  which means that we have no longer any way to track that it's still running, but the process doesn't allow other jobs to start.

Here's how I start up the service.   I replaced the AutomaticRetryAttribute with a version that attempts to move jobs that timed out to a longer running queue.   I was having this issue before I made this change, however.

The environment we are running these jobs are configured to use Redis by setting the ConnectionStringRedis in the .config file.

```csharp
       public BackendService()
        {
            QueueType = GetMachineInfo.QueueType;
            UpdateConfigurationBasedOnQueueType.UpdateConfigs(QueueType);
            
            var redisConnectionString = ConfigurationManager.AppSettings[Globals.ConnectionStringRedis];
            if (redisConnectionString != null)
            {
                int invisibilityTimeout = 300;
                var invisibilityTimeoutStr = ConfigurationManager.AppSettings[UpdateConfigurationBasedOnQueueType.RedisInvisibilityTimeout];

                if (invisibilityTimeoutStr != null)
                    int.TryParse(invisibilityTimeoutStr, out invisibilityTimeout);

                SystemLogger.Info($"Setting invisibilty timeout to {invisibilityTimeout}");

                GlobalConfiguration.Configuration
                    .UseRedisStorage(redisConnectionString,
                        new RedisStorageOptions()
                            {
                                InvisibilityTimeout  = TimeSpan.FromMinutes(invisibilityTimeout),
                                Prefix = "{hangfire}:"
                        })
                    .UseActivator(new UnityJobActivator(BackendUnityConfig.Container))
                    .UseBatches()
                    .UseConsole();
            }
            else
            {
                GlobalConfiguration.Configuration
                    .UseSqlServerStorage("HangfireConnection",
                        new SqlServerStorageOptions
                        {
                            QueuePollInterval = TimeSpan.FromSeconds(30),
                            CommandTimeout = TimeSpan.FromMinutes(10),
                            TransactionTimeout = TimeSpan.FromMinutes(10),
                            SlidingInvisibilityTimeout = TimeSpan.FromMinutes(10)
                        })
                    .UseActivator(new UnityJobActivator(BackendUnityConfig.Container))
                    .UseBatches()
                    .UseConsole();
            }

            object automaticRetryAttribute = null;
            foreach (var filter in GlobalJobFilters.Filters)
            {
                if (filter.Instance is Hangfire.AutomaticRetryAttribute)
                    automaticRetryAttribute = filter.Instance;
            }
            
            // ok now let's remove it
            if (automaticRetryAttribute == null)
            {
                throw new System.Exception("Didn't find hangfire automaticRetryAttribute something very wrong");
            }
            
            GlobalJobFilters.Filters.Remove(automaticRetryAttribute);
            GlobalJobFilters.Filters.Add(new BatchCustomAutoRetryJobFilterAttribute { Attempts = 5, LogEvents = true });
        }
```

My re-written automaticRetryAttribute - now called BatchCustomAutoRetryJobFilterAttribute "OnStateElection" method looks like:
```csharp
        public void OnStateElection(ElectStateContext context)
        {
            var job = context.BackgroundJob?.Job;

            var failedReason = context.CandidateState.Reason?.ToLowerInvariant() ?? "";
            bool moveToLargeQueue = (failedReason.Contains("memory") || failedReason.Contains("invisibilitytimeout"))
                                   && job?.Method?.Name?.ToLowerInvariant() == "batchrunanalysis";
            
            var failedState = context.CandidateState as FailedState;
            if (failedState != null)
            {
                var retryAttempt = context.GetJobParameter<int>("RetryCount") + 1;

                if (retryAttempt <= Attempts)
                {
                    ScheduleAgainLater(context, retryAttempt, failedState, moveToLargeQueue);
                }
                else if (retryAttempt > Attempts && OnAttemptsExceeded == AttemptsExceededAction.Delete)
                {
                    TransitionToDeleted(context, failedState);
                }
                else
                {
                    if (LogEvents)
                    {
                        Logger.ErrorException(
                            $"Failed to process the job '{context.BackgroundJob.Id}': an exception occurred.",
                            failedState.Exception);
                    }
                }
            }

            var enqueuedState = context.CandidateState as EnqueuedState;
            if (enqueuedState != null)
            {
                if (!moveToLargeQueue)
                    moveToLargeQueue = context.GetJobParameter<bool>("MoveToLargeQueue");

                if (moveToLargeQueue)
                    enqueuedState.Queue = BatchQueueNames.LargebatchRun;
            }
        }
```

and the ScheduleAgainLater method was tweaked to be:

```csharp 
       private void ScheduleAgainLater(ElectStateContext context, int retryAttempt, FailedState failedState, bool moveToLargeQueue)
        {
            context.SetJobParameter("RetryCount", retryAttempt);
            context.SetJobParameter("MoveToLargeQueue", moveToLargeQueue);

            var delay = TimeSpan.FromSeconds(SecondsToDelay(retryAttempt));

            const int maxMessageLength = 50;
            var exceptionMessage = failedState.Exception.Message.Length > maxMessageLength
                ? failedState.Exception.Message.Substring(0, maxMessageLength - 1) + "…"
                : failedState.Exception.Message;

            // If attempt number is less than max attempts, we should
            // schedule the job to run again later.
            context.CandidateState = new ScheduledState(delay)
            {
                Reason = moveToLargeQueue
                ? $"Retry attempt {retryAttempt} of {Attempts}: moving to large queue: {failedState.Reason}"
                : $"Retry attempt {retryAttempt} of {Attempts}: {exceptionMessage}",               
            };

            if (LogEvents)
            {
                Logger.WarnException(
                    $"Failed to process the job '{context.BackgroundJob.Id}': an exception occurred. Retry attempt {retryAttempt} of {Attempts} will be performed in {delay}.",
                    failedState.Exception);
            }
        }
```

Versions:
Hangfire.Console v 1.3.4
Hangfire.Core v1.6.16
Hangfire.Pro v2.1.0
Hangfire.Pro.redis v2.1.1
Hangfire.SqlServer v1.6.16
Hangfire.Unity v1.3.0

**Comment by odinserj** [comment]
First of all, try setting much larger timeout, say 24 hours. `FetchedJobsWatcher` component that is responsible for re-queueing timed-out jobs has a heuristic that checks whether the server that processes a job is active. If it was removed, your job will be re-queued much earlier.

Second, consider you have `Worker A` and `Worker B` background processes. The `Worker A` process picks up a job, and then after 5 hours (that's configured invisibility timeout value in your case), `Worker B` picks up the same job, but `Worker A` is still processing it. There also may be `Worker C` that picks up the same job after another 5 hours, and you have `Worker A` and `Worker B` that process it. Eventually, `Worker A` completes a job regardless the invisibility timeout. 

You can use the `IJobCancellationToken` in your background job method to detect when another worker picks up a job and gracefully stop the processing.

Another thing to ensure is you are using NTP to synchronise clocks on your servers.

**Comment by dcorbett-fivebridgesllc** [comment]
Setting a 24 hour timeout didn't make the difference..   I have two machines running 25 jobs each...  I started them at 12:25pm this afternoon..  and it's a little over 2 hours later, and only one job is visible in the "Processing Queue".   What happened to the others?

Does the invisibility timeout being different in the UI website where the console runs ( but isn't pulling from tthis queue ) make a difference?

**Comment by dcorbett-fivebridgesllc** [comment]
I tried setting all instances hangfire with the same redisinvisiblity timeout and get the same effect.

The invisibilityTimeout continues to expire approximately 2 hours after the job is started.   

The job continues to process ( because we are running a long running 3rd Party DLL call -- that can take as much as 17 hours to run, though usually completes much sooner).

The Processing Jobs now shows 0...    and the jobs are showing as "Processing" status in the queue..

I checked the times on all the machines.   There are currently 2 large machines running a Hangfire Windows Server process, and a 3rd smaller machine running an ASP.net application running the Hangfire console.

The latter is different than the other two timewise -- It's EST instead of GMT, and up to a couple minutes different from the others.

Will work with an admin to sync these up tomorrow.   But a couple of minutes shouldn't cause an issue should it, given we are talking 24 hours?

   - Daniel

**Comment by odinserj** [comment]
A single machine with smaller invisibility timeout can cause a job to be requeued earlier. Another possible reason is due to wrong clocks, one server can kill another server thinking it's timed out. When Redis is overloaded (as per #998 your workload is huge), delayed heartbeat commands can make the situation worse. 

You can start by increasing your server timeout to 15 or 30 minutes using the `BackgroundJobServerOptions.ServerTimeout` property on all the instances and then ensure there's no machines with different invisibility timeout value. This should solve the issue described here.

Then synchronize the clocks (including the server where Redis is hosted) so their real-time clock difference is at least less than 1 minute. It's best to use multiple NTP servers to prevent outliers to affect anything. Currently Redis job storage is sensitive to clock synchronization, I'll think how to improve the things.

**Comment by dcorbett-fivebridgesllc** [comment]
Running a small batch with just large jobs...    3 machines - 25 jobs each.   Redis invisibility 1440 = 24 hours on all machines, including the Console.     I'm still getting invisibility timeouts much earlier than expected, but sometimes longer... this one happened after 4h 26m.

I set the ServerTimeout property as requested.    All Hangfire servers are synced closely by Amazon.   The webserver is no longer running as a Hangfire server but just running the console.   It's now within 10 seconds of being in sync.

> Enqueued
Background job was re-queued, because InvisibilityTimeout exceeded
Queue:
PRIORITY6_LARGEBATCH_RUN
+24m 59.973s Processing
Server:
IP-0AC80BA6:372
Worker:
81f6e45e
+10.446sBatchRunLargeAnalysis at 9/20/2017 9:35:06 PM on IP-0AC80BA6 IP: 10.200.11.166 Instance: i-03243c00aca42f0bf  QueueType: LargeBatch
+10.587sRedisConn: redishf1.5v1fog.clustercfg.use1.cache.amazonaws.com:6379 
+10.589sEnvironment:Development
+10.590sName:BATCH-BES-JMA
+10.592saws:cloudformation:stack-id:arn:aws:cloudformation:us-east-1:350477940739:stack/JMA-BATCH-TEST/259737f0-366a-11e7-997c-50a686e4bbe6
+10.593saws:cloudformation:logical-id:ASGJMABESLS
+10.594saws:autoscaling:groupName:JMA-BATCH-TEST-ASGJMABESLS-G92UB8SK0OFY
+10.596sBill:JMA-Batch
+10.597saws:cloudformation:stack-name:JMA-BATCH-TEST
+10.599sQueueType:LargeBatch
+10.793sHangfireWorkers: 25
+10.820sRedisInvisibilityTimeout: 300
+10.847sQueues: priority6_largebatch_run,priority1_complete,priority2_interactive_run,priority3_interactive_populate,priority4_batch_create_analysis_jobs,priority5_batch_create_analysis,priority5_batch_start,priority6_batch_run,priority7_batch_populaterelated,priority8_batch_populate
+10.867sHeuristic: 
+10.868sBeginning run analysis
+14.464sCreate Deal Engine Request for asset: e9cc7d53-c1db-4553-9c35-03ea863d9b41
+22.197sStarting to run scenarios for AnalysisRndId:[BATCH-00b6a37df7e0025315dd1daf24163dc5] Cusip:[38378F8G8] of type: AgencyRmbs from deal GNM13031
+22.307sInit for deal engine
+22.375sCreating AssetScenarioResults.
+22.377sLooping through parents to open deal and run cashflows.
+22.378sGenerateIntexInputsSettings for parent: 38378F8G8
+51.806sOpenDeal() deal engine 5d1aafb3-60dc-4903-a16d-24cfd02012f0 for AssetId: 38378F8G8 and Scenario: PWC Base
+1m 48.936sAsset: 38378F8G8 of assetType: AgencyRmbs has 46 CF Assumptions
+1m 49.098sInvokeSetQueryScript() deal engine 5d1aafb3-60dc-4903-a16d-24cfd02012f0 for AssetId: 38378F8G8 and Scenario: PWC Base
+1m 49.102sInvokeCollat() deal engine 5d1aafb3-60dc-4903-a16d-24cfd02012f0 for AssetId: 38378F8G8 and Scenario: PWC Base
+4h 26mJMAJobCancellationToken = JobAbortedException at 9/21/2017 2:01:47 AM.
+4h 26mStackTrace:    at Hangfire.Server.ServerJobCancellationToken.ThrowIfCancellationRequested()
   at Javelin.MultiAsset.BackendService.JMAJobCancellationToken.ThrowIfCancellationRequested() in Y:\TeamCity\BuildAgent3\work\15a46b9a78339ebc\Javelin.MultiAsset.BackendService\JMAJobCancellationToken.cs:line 28
+4h 26mReceived Operation Cancelled exception
+4h 26mHangfire.Server.JobAbortedException: The operation was canceled.
   at Hangfire.Server.ServerJobCancellationToken.ThrowIfCancellationRequested()
   at Javelin.MultiAsset.BackendService.JMAJobCancellationToken.ThrowIfCancellationRequested() in Y:\TeamCity\BuildAgent3\work\15a46b9a78339ebc\Javelin.MultiAsset.BackendService\JMAJobCancellationToken.cs:line 36
   at Javelin.MultiAsset.Services.DealEngineService.RunCashflows(DealEngineHelper helper, DealEngineParent parent, AssetScenarioResults results, DealEngineAssetScenario parentAssetScenario, PerformContext performContext, IJobCancellationToken cancellationToken) in Y:\TeamCity\BuildAgent3\work\15a46b9a78339ebc\Javelin.MultiAsset.Services\DealEngineService.cs:line 783
   at Javelin.MultiAsset.Services.DealEngineService.RunScenarios(DealEngineRequest request, Boolean runCashflows, Boolean calculateCashflowStats, Boolean calculatePriceYieldStats, IJobCancellationToken cancellationToken, PerformContext performContext, String clientId, List`1 multiRunAssetList, List`1 relateDealEngineRequests, Nullable`1 userId, Nullable`1 organizationGroupId) in Y:\TeamCity\BuildAgent3\work\15a46b9a78339ebc\Javelin.MultiAsset.Services\DealEngineService.cs:line 488
   at Javelin.MultiAsset.Batch.BatchService.BatchRunAnalysis(String json, String selectedAssetReferenceId, String scenarioReferenceId, PerformContext performContext, IJobCancellationToken cancellationToken) in Y:\TeamCity\BuildAgent3\work\15a46b9a78339ebc\Javelin.MultiAsset.Batch\BatchService.cs:line 1385

**Comment by dcorbett-fivebridgesllc** [comment]
This job actually ran another 4hs and 43 minutes, and completed.   The previous running failed because we checked the cancellationToken and it threw the canceled Operation exception .   In the retried situation, not sure why it didn't fail again?

**Comment by odinserj** [comment]
Could you also provide a screenshot of a job details page for that job and the output of the Redis' `info` command?

**Comment by dcorbett-fivebridgesllc** [comment]
We are using Elasticache in Amazon -- Not using a command line redis client, so not even sure how to run this command at the moment.   Taking off shortly, will investigate and see how I can do that.

here are shots of sections of the page from a current job that had the exception thrown.    This test run, was pushed from a different branch where we are working on fixing other issues, so doesn't have the most recent hangfire libraries.

![image](https://user-images.githubusercontent.com/26471190/30705888-c0863ed8-9ec4-11e7-814a-7acfbf5d34be.png)

![image](https://user-images.githubusercontent.com/26471190/30705943-e90b7a94-9ec4-11e7-9083-e2c8f99e1983.png)

![image](https://user-images.githubusercontent.com/26471190/30705975-09885fd0-9ec5-11e7-97db-c9946dcfdda9.png)

**Comment by odinserj** [comment]
Thank you for the update. Oh yes, the most interesting information there is the `maxmemory-policy` option, it [should be set](http://docs.hangfire.io/en/latest/configuration/using-redis.html#redis-configuration) to `noeviction`. I just wanted to ensure that the value is correct.

**Comment by dcorbett-fivebridgesllc** [comment]
Any further ideas / progress on this issue?   We are continuing to have an issue with the long running jobs, even after implementing all your suggestions.

**Comment by dcorbett-fivebridgesllc** [comment]
After reviewing this thread I realized I never confirmed the maxmemory-policy with you ( I did have our infrastructure person check it - I was out of town at the time ).

Here's a screen capture from our parameter settings for Redis in Amazon that includes this value:

![image](https://user-images.githubusercontent.com/26471190/31339466-f1a10e02-acd0-11e7-88cb-4fa5382bc6d8.png)

@odinserj  This is our number one issue right now..  if we don't find an answer soon, or good enough work-around, I'll have to create a non-hangfire solution for these long running jobs!

**Comment by odinserj** [comment]
Oh Daniel, I've tried hard to reproduce this issue with synchronized servers and a single invisibility timeout value both practically on AWS, and theoretically through the code, but unable to do so without extreme conditions, please see them below. Your long-running jobs are retried, because other servers think that the processing server is died, and there's a problem in application environment.

One reason is non-synchronized clocks between different servers, the reason which we already excluded, since you've told me the clocks are fine now, and `ServerTimeout` is set to a higher value (15 minutes), which can tolerate the corresponding clock drift. We could also try to set it to even higher value, like 1 hour to exclude this reason completely.

Another reason is related to the `Heartbeat` command that is issued by a server on a regular interval (30 seconds by default). If the last heartbeat was sent a `ServerTimeout` ago, the server is considered as died and will be removed, causing all the processing jobs to be retried. And if the delivery of this command encounters an error, or is delayed for the whole `ServerTimeout` period, other servers will remove such a problematic one. There are the following reasons for this behavior:

1. Heartbeat command couldn't be delivered. Since `ServerHeartbeat` component requires the command to be acknowledged, it will throw exception that will be logged (if your logging is enabled) with the exact reason, whether it's caused by connectivity issue, or a timeout. Larger `ServerTimeout` value may help here.
     a. There are network issues due to network infrastructure or firewalls.
     b. Redis is unable to handle the command due to the high load. 
2. There are problems with sending a heartbeat.
    a. Huge GC pause may cause this, especially when CPU usage by other processes is high and there are a lot of memory to be reclaimed, you can exclude this by collecting perf counters. 
    b. Other reason is there are threads with higher priority on your machine, which prevent `ServerHeartbeat` thread to be scheduled. This is very unlikely, especially on Windows Server, but still could happen.

We can create additional heartbeat component and put more verbose logging logic here to diagnose what happens with heartbeat delivery:

```csharp
public class CustomHeartbeat : IBackgroundProcess
{
    private Stopwatch _failedSince;

    public void Execute(BackgroundProcessContext context)
    {
        // StackExchange.Redis has a dedicated thread for writing to the socket,
        // and it's priority is AboveNormal by default, and couldn't be set to a
        // higher value anyway.
        Thread.CurrentThread.Priority = ThreadPriority.AboveNormal;

        try
        {
            using (var connection = context.Storage.GetConnection())
            {
                connection.Heartbeat(context.ServerId);
            }

            if (_failedSince != null)
            {
                Console.WriteLine($"{DateTime.UtcNow} Heartbeat recovered from failed state after {_failedSince.ElapsedMilliseconds} ms.");
                _failedSince = null;
            }
            else
            {
                Console.WriteLine($"{DateTime.UtcNow} Heartbeat command sent successfully");
            }
        }
        catch (Exception ex)
        {
            if (_failedSince == null)
            {
                // Put explicit logging logic here to be sure that 
                _failedSince = Stopwatch.StartNew();
                Console.WriteLine($"{DateTime.UtcNow} Heartbeat entered the failed state due to an exception: {ex}");
            }
        }

        context.Wait(TimeSpan.FromSeconds(30));
    }
}
```

**Comment by dcorbett-fivebridgesllc** [comment]
Thanks,  I'll add calling this CustomHeartbeat with my logging functions, and we'll see if there are any errors that happen.   I don't think this problem has much to do with load on Redis ( Redis is always very low CPU) or # of servers running.    So I will be testing on a single job processing server + one console web app that isn't processing jobs, and see if I can reproduce the problem.

**Comment by odinserj** [comment]
Are you getting network/disk/cpu/memory-bound on the processing server? Overloaded network interface may cause delays and packet loss. High memory usage may cause swapping, and degraded overall performance, especially on slow disks. By the way, if you are running on VM, noisy neighbours may cause additional pauses. So it's better not to guess and see what happens with heartbeats, the problem is really weird.

**Comment by dcorbett-fivebridgesllc** [comment]
We are running a long running 3rd party process, that we call from our application.   It can use a lot of memory...  We are running 25 jobs on Amazon's r4.16xlarge instance which has 64 virtual CPUs and 488 GiB of RAM.    Occasionally the combination of jobs on the machine is enough to use all that RAM, and the machine can crash for this.   I get a specific error when this happens on the job that requested more RAM.

Unfortunately we don't have any measurement on memory usage on a per-job basis, and awareness of which consume how much memory.

I *think* this invisiblity problem is independent of that though.

When this job starts up, we grab all the data from a remote controlled file system, and it is basically CPU/memory bound for hours.   Other jobs do a lot of database & S3 I/O, not so much for this job.   It does write results mostly to S3, when it completes.

I'll monitor this test of a single box more closely -- checking on memory and CPU usage, and see if we get the same consistent behavior of retrying at approximately 2 hours.  ( it's the mostly consistent 2 hours that makes me doubt any of these things are the cause ).

The single machine definitely won't be bound by network/disk as the available resources are way more than this single job needs.

**Comment by dcorbett-fivebridgesllc** [comment]
Good news is that running on a single server running off the queue, with the additional heartbeat, I'm not seeing this issue.    Adding a second server, to try to see if the problem comes back.

**Comment by odinserj** [comment]
Daniel, will wait for bad news then! Exceptions will show there are problems with heartbeat delivery (due to network, client or server issues), and missing heartbeats will show there are problems with sending the heartbeats.

**Comment by dcorbett-fivebridgesllc** [comment]
I added a second server, and now seeing invisibility timeouts...   in really short amounts of time!  ;-(

This is a server designated as a SmallBatch queuetype... and what that means is that it is much smaller, and doesn't include the LargeBatchAnalysis queue.

Included in the log are the CustomHeartBeat logs, so you can see that they are running continually 

> 10:23:36.4185 TRACE InvisibilityTimeout 10/11/2017 10:23:36 AM on IP-0AC80B79 IP: 10.200.11.121 Instance: i-041eb9694ed7db3d0  QueueType: SmallBatch
Javelin.MultiAsset.BackendService.CustomHeartbeat.Execute:38
10/11/2017 2:23:36 PM Heartbeat command sent successfully 
10:23:41.3687 TRACE InvisibilityTimeout 10/11/2017 10:23:41 AM on IP-0AC80BEC IP: 10.200.11.236 Instance: i-0ad89cc307bac180d  QueueType: LargeBatch
Javelin.MultiAsset.BackendService.CustomHeartbeat.Execute:38
10/11/2017 2:23:41 PM Heartbeat command sent successfully 
10:24:06.5657 TRACE InvisibilityTimeout 10/11/2017 10:24:06 AM on IP-0AC80B79 IP: 10.200.11.121 Instance: i-041eb9694ed7db3d0  QueueType: SmallBatch
Javelin.MultiAsset.BackendService.CustomHeartbeat.Execute:38
10/11/2017 2:24:06 PM Heartbeat command sent successfully 
10:24:07.5357 ERROR InvisibilityTimeout 10/11/2017 10:24:07 AM on IP-0AC80B79 IP: 10.200.11.121 Instance: i-041eb9694ed7db3d0  QueueType: SmallBatch
d1d0ac08-55f6-4384-8ece-2bb93bd2d473 10/11/2017 1:58:07 AM BatchPopulateAssumptionsRelated
Javelin.MultiAsset.BackendService.JMAJobCancellationToken.ThrowIfCancellationRequested:35
Cancellation Token threw. 
10:24:11.3688 TRACE InvisibilityTimeout 10/11/2017 10:24:11 AM on IP-0AC80BEC IP: 10.200.11.236 Instance: i-0ad89cc307bac180d  QueueType: LargeBatch
Javelin.MultiAsset.BackendService.CustomHeartbeat.Execute:38
10/11/2017 2:24:11 PM Heartbeat command sent successfully 
10:24:36.6570 TRACE InvisibilityTimeout 10/11/2017 10:24:36 AM on IP-0AC80B79 IP: 10.200.11.121 Instance: i-041eb9694ed7db3d0  QueueType: SmallBatch
Javelin.MultiAsset.BackendService.CustomHeartbeat.Execute:38
10/11/2017 2:24:36 PM Heartbeat command sent successfully 
10:24:41.3889 TRACE InvisibilityTimeout 10/11/2017 10:24:41 AM on IP-0AC80BEC IP: 10.200.11.236 Instance: i-0ad89cc307bac180d  QueueType: LargeBatch
Javelin.MultiAsset.BackendService.CustomHeartbeat.Execute:38

from the console output:

![image](https://user-images.githubusercontent.com/26471190/31450104-a4fb2b76-ae76-11e7-8c96-835342a01b90.png)

**Comment by dcorbett-fivebridgesllc** [comment]
I also verified that both machines have the exact same time ( at least within a couple seconds as shown by the clock through remote desktop ).

**Comment by dcorbett-fivebridgesllc** [comment]
What's new is that I never noticed this on these smaller jobs..     This particular job timed out several times.

Another factor is that this job was interrupted multiple times, earlier, as I pushed new code while running the batch.   I wanted to put the HeartBeat logs in a separate shared "CurrentIssues" log, so that we can see them together form both machines, along with any logs for the timeout.

This happened to multiple similar jobs...  but now they have successfully ran, I'll see if it happens without the code deploying event happening.

**Comment by dcorbett-fivebridgesllc** [comment]
Our backend servers are running as a Windows Service, so application pool settings don't apply.

**Comment by dcorbett-fivebridgesllc** [comment]
The example I entered above, was long after the deployment happened...  Somehow the timeout happened early because it previously restarted.

**Comment by dcorbett-fivebridgesllc** [comment]
That said, it hasn't happened since...   :)   I now have 2 small and 2 large servers running.

**Comment by odinserj** [comment]
So the following message wasn't caused by deployment? If not, tomorrow I'll add traces to all the methods that are related to the server removal logic.

```
10:24:07.5357 ERROR InvisibilityTimeout 10/11/2017 10:24:07 AM on IP-0AC80B79 IP: 10.200.11.121 Instance: i-041eb9694ed7db3d0  QueueType: SmallBatch
d1d0ac08-55f6-4384-8ece-2bb93bd2d473 10/11/2017 1:58:07 AM BatchPopulateAssumptionsRelated
Javelin.MultiAsset.BackendService.JMAJobCancellationToken.ThrowIfCancellationRequested:35
Cancellation Token threw. 
```

**Comment by dcorbett-fivebridgesllc** [comment]
It wasn't, the deployment happened an hour earlier around 9:30pm.

**Comment by odinserj** [comment]
Okay, tomorrow I'll add all the required traces. One more thing, I just want to ensure there were no exceptions and all the heartbeat completed in time earlier in that log during the N last minutes, corresponding to the `ServerTimeout` value. Could you send me the whole file? I'll check that heartbeat is invoked every 30 seconds.

**Comment by dcorbett-fivebridgesllc** [comment]
Sent as an attachment to your gmail.   It's pretty easy to check,

**Comment by odinserj** [comment]
@dcorbett-fivebridgesllc, any news on this issue? Did the tracing show any results for you?

**Comment by dcorbett-fivebridgesllc** [comment]
I ran it once, and didn't capture the necessary results -- and then other priorities overtook.
I appreciate your support a great deal, especially on the timeout issues.
In reality if this is still happening, it's a tiny issue in the scheme of things, and difficult to reproduce consistently.

There are other issues that have a greater impact, such as jobs that never start, but sit on the queue for hours.   These jobs do run when requeued, and I've not had the time to focus on them.

If you want to close this issue, feel free.

**Comment by odinserj** [comment]
Any chance you are using `DisableConcurrentExecutionAttribute`? It can cause these problems, please see #1053.

**Comment by dcorbett-fivebridgesllc** [comment]
No, we are not using it.    I believe that function is mostly useful for Recurring jobs that can overlap.   We have not yet used the recurring job functionality.

**Comment by Plasma** [comment]
I’ve just been reading up on hangfire and saw this issue, I’m not familiar with the redis storage option, but does it use the worker machine hostname as part of a locking key between workers? 

Amazon Elastic Beanstalk and other AMIs can have the same windows hostname for each instance in the cluster. 

If this is the issue, the instance could grab its EC2 instance ID instead to use.

**Comment by odinserj** [comment]
No, external identifiers like hostname, Mac address or statically assigned GUIDs aren't used for synchronisation purposes. Synchronisation is delegated to the storage implementation and Hangfire.SqlServer uses SQL Server's application locks, Hangfire.Pro.Redis uses connection identifiers and expiring keys with some LUA scripting for reliable locking, and so on.
